target 'Paper', :exclusive => true do
  pod "Paper", :path => "../"
  pod "UIKit+Material", '~> 0.1.1'
end

target 'Tests', :exclusive => true do
  pod "Paper", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'EXPMatchers+FBSnapshotTest'
end
